### ISSUE TITLE
Schematic available?

### ISSUE THREAD

**Issue by bmoren** [vaeinoe/moraydular#1]
I was looking for the schematic for this, is it available?

I was hoping to make a version of the my little euro with the PSU components but w/o the euro power connectors to save on PCB cost. 

thanks!

**Comment by vaeinoe** [comment]
I should actually write sort of an attribution or history about the PSU design to the description, but the "dual halfwave" idea is pretty much directly copied from Ray Wilson / MFOS wall wart power supply, so you can use those schematics directly - I just added LEDs in series of the small dummy load resistors (R1, R2) to get power indication: http://musicfromouterspace.com/analogsynth_new/WALLWARTSUPPLY/WALLWARTSUPPLY.php

Frequency Central also makes a power supply with the same concept but their PCB layout is not open sourced: http://www.frequencycentral.co.uk/?page_id=894

**Comment by vaeinoe** [comment]
I admit being lazy with these bus boards (even the powered My Little Euro) because they were originally made solely for my own use. So I didn't actually start with schematic capture at all, but laid out the PCB directly, which indicates how directly it resembles the MFOS design I suppose...
